remote: @@bs@@.bs
	curl https://api.csswg.org/bikeshed/ -f -F file=@@@bs@@.bs > @@bs@@.html -F md-Text-Macro="SNAPSHOT-LINK LOCAL COPY"

local: @@bs@@.bs
	bikeshed spec @@bs@@.bs @@bs@@.html --md-Text-Macro="SNAPSHOT-LINK LOCAL COPY"

deploy: @@bs@@.bs
	curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh
	bash ./deploy.sh

review: @@bs@@.bs
	curl --remote-name --fail https://resources.whatwg.org/build/review.sh
	bash ./review.sh
